version: '3'
services:
  front:
    build: ./front
    ports:
      - '3000:3000'
    environment:
      - VITE_HOST_BACKEND_PROD=http://localhost:3001
      - VITE_HOST_MESSAGES_PROD=http://localhost:3002
  back:
    build: ./back
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=mongodb://localhost:27021,localhost:27022,localhost:27023/nexn?replicaSet=dbrs
      - JWT_SECRET_KEY=josepaye123
      - JWT_TIMEOUT=6h
      - HOST_FRONTEND=http://localhost:3000
    links:
      - mongo1
      - mongo2
      - mongo3
  socket:
    build: ./socket-messages
    ports:
      - '3002:3001'
