version: '1'
services:
  front:
    build: ./front
    ports:
      - "5173:3000"
    links: 
      - back
  back:
    build: ./back
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

      
volumes:
  mongo-data: