version: '2'
services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    environment:
      - VITE_HOST_BACKEND_PROD=http://localhost:3001
      - VITE_HOST_MESSAGES_PROD=http://localhost:3002
  back:
    build: ./back
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=mongodb://mongo1:27017/nexn?directConnection=true
      - JWT_SECRET_KEY=josepaye123
      - JWT_TIMEOUT=6h
      - HOST_FRONTEND=http://localhost:3000
    links:
      - mongo1
  socket:
    build: ./socket-messages
    ports:
      - "3002:3001"
  mongo1:
    image: mongo:6
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]
  mongo2:
    image: mongo:6
    hostname: mongo2
    container_name: mongo2
    ports:
      - 27018:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]
  mongo3:
    image: mongo:6
    hostname: mongo3
    container_name: mongo3
    ports:
      - 27019:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]
  mongosetup:
    image: mongo:6
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]


volumes:
  mongo-data: