version: '2'

services:
  mongo:
    image: candis/mongo-replica-set
    ports:
      - '27017:27017'
      - '27018:27018'
      - '27019:27019'
    deploy:
      mode: replicated
      replicas: 1

networks:
  mongors-network:
    driver: bridge
